/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Delivery {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'createdAt' : bigint,
  'deliveryDate' : string,
  'productName' : string,
  'address' : string,
  'notes' : string,
  'phone' : string,
  'driverName' : string,
}
export interface IncomingStock {
  'id' : bigint,
  'status' : string,
  'supplierName' : string,
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'expectedDate' : string,
}
export interface InventorySummary {
  'lowStockThreshold' : bigint,
  'productCode' : string,
  'productId' : bigint,
  'productName' : string,
  'soldQty' : bigint,
  'incomingPending' : bigint,
  'category' : string,
  'currentStock' : bigint,
}
export interface Product {
  'id' : bigint,
  'lowStockThreshold' : bigint,
  'code' : string,
  'name' : string,
  'sellingPrice' : number,
  'category' : string,
  'costPrice' : number,
}
export interface Sale {
  'id' : bigint,
  'customerName' : string,
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'saleDate' : string,
}
export interface _SERVICE {
  'addIncomingStock' : ActorMethod<
    [bigint, string, bigint, string, string],
    IncomingStock
  >,
  'createDelivery' : ActorMethod<
    [string, string, string, string, string, string, string],
    Delivery
  >,
  'createProduct' : ActorMethod<
    [string, string, string, number, number, bigint],
    Product
  >,
  'deleteDelivery' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getDeliveries' : ActorMethod<[], Array<Delivery>>,
  'getIncomingStock' : ActorMethod<[], Array<IncomingStock>>,
  'getInventorySummary' : ActorMethod<[], Array<InventorySummary>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSales' : ActorMethod<[], Array<Sale>>,
  'recordSale' : ActorMethod<
    [bigint, string, bigint, string, string],
    undefined
  >,
  'updateDelivery' : ActorMethod<
    [bigint, string, string, string, string, string, string, string, string],
    Delivery
  >,
  'updateIncomingStockStatus' : ActorMethod<[bigint, string], IncomingStock>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, string, number, number, bigint],
    Product
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];