/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const IncomingStock = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'supplierName' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'expectedDate' : IDL.Text,
});
export const Delivery = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'deliveryDate' : IDL.Text,
  'productName' : IDL.Text,
  'address' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'driverName' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'sellingPrice' : IDL.Float64,
  'category' : IDL.Text,
  'costPrice' : IDL.Float64,
});
export const InventorySummary = IDL.Record({
  'lowStockThreshold' : IDL.Nat,
  'productCode' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'soldQty' : IDL.Nat,
  'incomingPending' : IDL.Nat,
  'category' : IDL.Text,
  'currentStock' : IDL.Int,
});
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'saleDate' : IDL.Text,
});

export const idlService = IDL.Service({
  'addIncomingStock' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IncomingStock],
      [],
    ),
  'createDelivery' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Delivery],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat],
      [Product],
      [],
    ),
  'deleteDelivery' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getDeliveries' : IDL.Func([], [IDL.Vec(Delivery)], ['query']),
  'getIncomingStock' : IDL.Func([], [IDL.Vec(IncomingStock)], ['query']),
  'getInventorySummary' : IDL.Func([], [IDL.Vec(InventorySummary)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'recordSale' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateDelivery' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Delivery],
      [],
    ),
  'updateIncomingStockStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IncomingStock],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
      ],
      [Product],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const IncomingStock = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'supplierName' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'expectedDate' : IDL.Text,
  });
  const Delivery = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'deliveryDate' : IDL.Text,
    'productName' : IDL.Text,
    'address' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'driverName' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'sellingPrice' : IDL.Float64,
    'category' : IDL.Text,
    'costPrice' : IDL.Float64,
  });
  const InventorySummary = IDL.Record({
    'lowStockThreshold' : IDL.Nat,
    'productCode' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'soldQty' : IDL.Nat,
    'incomingPending' : IDL.Nat,
    'category' : IDL.Text,
    'currentStock' : IDL.Int,
  });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'saleDate' : IDL.Text,
  });
  
  return IDL.Service({
    'addIncomingStock' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IncomingStock],
        [],
      ),
    'createDelivery' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Delivery],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Nat],
        [Product],
        [],
      ),
    'deleteDelivery' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getDeliveries' : IDL.Func([], [IDL.Vec(Delivery)], ['query']),
    'getIncomingStock' : IDL.Func([], [IDL.Vec(IncomingStock)], ['query']),
    'getInventorySummary' : IDL.Func(
        [],
        [IDL.Vec(InventorySummary)],
        ['query'],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'recordSale' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateDelivery' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Delivery],
        [],
      ),
    'updateIncomingStockStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IncomingStock],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
        ],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };