/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Delivery {
    id: bigint;
    customerName: string;
    status: string;
    createdAt: bigint;
    deliveryDate: string;
    productName: string;
    address: string;
    notes: string;
    phone: string;
    driverName: string;
}
export interface Sale {
    id: bigint;
    customerName: string;
    productId: bigint;
    productName: string;
    quantity: bigint;
    saleDate: string;
}
export interface InventorySummary {
    lowStockThreshold: bigint;
    productCode: string;
    productId: bigint;
    productName: string;
    soldQty: bigint;
    incomingPending: bigint;
    category: string;
    currentStock: bigint;
}
export interface Product {
    id: bigint;
    lowStockThreshold: bigint;
    code: string;
    name: string;
    sellingPrice: number;
    category: string;
    costPrice: number;
}
export interface IncomingStock {
    id: bigint;
    status: string;
    supplierName: string;
    productId: bigint;
    productName: string;
    quantity: bigint;
    expectedDate: string;
}
export interface backendInterface {
    addIncomingStock(productId: bigint, productName: string, quantity: bigint, supplierName: string, expectedDate: string): Promise<IncomingStock>;
    createDelivery(customerName: string, phone: string, address: string, productName: string, deliveryDate: string, driverName: string, notes: string): Promise<Delivery>;
    createProduct(name: string, code: string, category: string, costPrice: number, sellingPrice: number, lowStockThreshold: bigint): Promise<Product>;
    deleteDelivery(id: bigint): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    getDeliveries(): Promise<Array<Delivery>>;
    getIncomingStock(): Promise<Array<IncomingStock>>;
    getInventorySummary(): Promise<Array<InventorySummary>>;
    getProducts(): Promise<Array<Product>>;
    getSales(): Promise<Array<Sale>>;
    recordSale(productId: bigint, productName: string, quantity: bigint, customerName: string, saleDate: string): Promise<void>;
    updateDelivery(id: bigint, customerName: string, phone: string, address: string, productName: string, deliveryDate: string, driverName: string, notes: string, status: string): Promise<Delivery>;
    updateIncomingStockStatus(id: bigint, status: string): Promise<IncomingStock>;
    updateProduct(id: bigint, name: string, code: string, category: string, costPrice: number, sellingPrice: number, lowStockThreshold: bigint): Promise<Product>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addIncomingStock(arg0: bigint, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<IncomingStock> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncomingStock(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncomingStock(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createDelivery(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<Delivery> {
        if (this.processError) {
            try {
                const result = await this.actor.createDelivery(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDelivery(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createProduct(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteDelivery(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDelivery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDelivery(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getDeliveries(): Promise<Array<Delivery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveries();
            return result;
        }
    }
    async getIncomingStock(): Promise<Array<IncomingStock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomingStock();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomingStock();
            return result;
        }
    }
    async getInventorySummary(): Promise<Array<InventorySummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventorySummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventorySummary();
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSales();
            return result;
        }
    }
    async recordSale(arg0: bigint, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSale(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSale(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateDelivery(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<Delivery> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDelivery(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDelivery(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateIncomingStockStatus(arg0: bigint, arg1: string): Promise<IncomingStock> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncomingStockStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncomingStockStatus(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
